---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
#  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
env:
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.2.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.8.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  # Ruby 1.9.3
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.2.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.8.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
    
  # Ruby 2.0.0
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.8.0" STRICT_VARIABLES=yes
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
    
  # Ruby 2.2.0
  - rvm: 2.2.0
    env: PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - rvm: 2.2.0
    env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    
  # Ruby 2.3.0
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
